### ISSUE TITLE
Localized <name> are lost

### ISSUE THREAD

**Issue by j3k0** [airsdk/apm#60] opened 2021-09-30 19:02 UTC
Application names can be localized in the application descriptor, cf https://help.adobe.com/en_US/air/build/WSD079A3A2-1B38-4543-A792-06594E4325FE.html

I did set localized names in `config/application-descriptor.xml`, however the value is erased by `apm generate application-descriptor` (which doesn't support localization).

**Comment by marchbold** [comment] 2021-10-01 00:40
I'd say this is a duplicate of #61 with the issue of the namespace.

**Closed by marchbold** 2021-10-01 00:40 UTC
